version: '3.9'
services:
  arma3:
    build: .
    image: ghcr.io/locally-developed/arma3server/arma3server:latest
    platform: linux/amd64
    container_name: arma3
    network_mode: host
    volumes:
      - './missions:/arma3/mpmissions'
      - './configs:/arma3/configs'
      - './mods:/arma3/mods'
      - './servermods:/arma3/servermods'
    env_file: stack.env
    restart: unless-stopped
